<?php

namespace Container9xCti0j;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_AFFIa3VService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.aFFIa3V' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.aFFIa3V'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'uploadService' => ['privates', 'App\\Service\\UploadService', 'getUploadServiceService', true],
        ], [
            'uploadService' => 'App\\Service\\UploadService',
        ]);
    }
}
