<?php

namespace Container9xCti0j;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getGazdinstvoTypeService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private 'App\Form\GazdinstvoType' shared autowired service.
     *
     * @return \App\Form\GazdinstvoType
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/symfony/form/FormTypeInterface.php';
        include_once \dirname(__DIR__, 4).'/vendor/symfony/form/AbstractType.php';
        include_once \dirname(__DIR__, 4).'/src/Form/GazdinstvoType.php';

        return $container->privates['App\\Form\\GazdinstvoType'] = new \App\Form\GazdinstvoType();
    }
}
