<?php

namespace ContainerX85l8ef;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getAtributTypeService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private 'App\Form\AtributType' shared autowired service.
     *
     * @return \App\Form\AtributType
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/symfony/form/FormTypeInterface.php';
        include_once \dirname(__DIR__, 4).'/vendor/symfony/form/AbstractType.php';
        include_once \dirname(__DIR__, 4).'/src/Form/AtributType.php';

        return $container->privates['App\\Form\\AtributType'] = new \App\Form\AtributType();
    }
}
