<?php

namespace ContainerX85l8ef;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getKomentarProizvodaTypeService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private 'App\Form\KomentarProizvodaType' shared autowired service.
     *
     * @return \App\Form\KomentarProizvodaType
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/symfony/form/FormTypeInterface.php';
        include_once \dirname(__DIR__, 4).'/vendor/symfony/form/AbstractType.php';
        include_once \dirname(__DIR__, 4).'/src/Form/KomentarProizvodaType.php';

        return $container->privates['App\\Form\\KomentarProizvodaType'] = new \App\Form\KomentarProizvodaType();
    }
}
