<?php

namespace ContainerX85l8ef;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getUploadServiceService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private 'App\Service\UploadService' shared autowired service.
     *
     * @return \App\Service\UploadService
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/src/Service/UploadService.php';

        return $container->privates['App\\Service\\UploadService'] = new \App\Service\UploadService(($container->privates['parameter_bag'] ?? ($container->privates['parameter_bag'] = new \Symfony\Component\DependencyInjection\ParameterBag\ContainerBag($container))));
    }
}
